/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/Home/Announcement.vue')['default']
    CardAside: typeof import('./src/components/public/aside/CardAside.vue')['default']
    Content: typeof import('./src/components/Home/Content.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    FooterVue: typeof import('./src/components/Footer/FooterVue.vue')['default']
    HeaderVue: typeof import('./src/components/Header/HeaderVue.vue')['default']
    PageHeader: typeof import('./src/components/Header/PageHeader.vue')['default']
    Recent: typeof import('./src/components/Home/Recent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/Home/UserInfo.vue')['default']
  }
}
