/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    FooterVue: typeof import('./src/components/Footer/FooterVue.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderVue: typeof import('./src/components/Header/HeaderVue.vue')['default']
    IconSvg: typeof import('./src/components/Global/IconSvg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
