/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/Home/Announcement.vue')['default']
    CardAside: typeof import('./src/components/public/aside/CardAside.vue')['default']
    Content: typeof import('./src/components/Home/Content.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    FooterVue: typeof import('./src/components/Footer/FooterVue.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderVue: typeof import('./src/components/Header/HeaderVue.vue')['default']
    IconSvg: typeof import('./src/components/Global/IconSvg.vue')['default']
    PageHeader: typeof import('./src/components/Header/PageHeader.vue')['default']
    Recent: typeof import('./src/components/Home/Recent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/Home/UserInfo.vue')['default']
  }
}
